files:
  - source: Resources/Private/Language/locallang*.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
commit_message: "[crowdin]"
"export_languages": [
    "fr",
    "de",
    "ro",
    "es",
    "da",
    "it"
]
