name: Tests

on: [push, pull_request]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: composer
                run: composer update --no-progress
    unit-tests:
        needs: setup
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [7.2, 7.3]
        steps:
            -   name: execute unit tests
                run: Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -x
    coveralls:
        needs: unit-tests
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} \
                        .build/bin/php-coveralls \
                        --verbose
