name: Unit tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: composer
                run: composer update
            -   name: execute unit tests
                run: Build/Scripts/runTests.sh -p 7.2 -x
            -   name: coveralls
                run: |
                    COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} \
                        .build/bin/php-coveralls \
                        --verbose
