name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: execute unit tests
                run: Build/Scripts/runTests.sh -p 7.2
